name: accionables

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Preparacion del entorno
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Paso 1 - Checkout repo
        uses: actions/checkout@v4

      - name: Paso 2 - Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.2'

      - name: Paso 3 - Crea entorno virtual
        run: python -m venv venv

      - name: Paso 4 - Activar entorno virtual
        run: ./venv/Scripts/activate   

      - name: Paso 5 - Actualizar pip
        run: pip install --upgrade pip

      - name: Paso 6 - Instalar dependencias
        run: pip install -e .
      
  test:
    name: Extrator
    runs-on: windows-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Paso 1 - Checkout repo
        uses: actions/checkout@v4

      - name: Paso 3 - Crea entorno virtual
        run: python -m venv venv

      - name: Paso 4 - Activar entorno virtual
        run: ./venv/Scripts/activate   

      - name: Paso 7 - Ejecutar Script Extractora
        run: ./venv/Scripts/python.exe src/edu_pad/main_extractora.py


  run_script:
    name: Ingesta
    runs-on: windows-latest
    needs: test
    permissions:
      contents: write
    steps:
      - name: Paso 1 - Checkout repo
        uses: actions/checkout@v4

      - name: Paso 3 - Crea entorno virtual
        run: python -m venv venv

      - name: Paso 4 - Activar entorno virtual
        run: ./venv/Scripts/activate    

      - name: Paso 8 - Ejecutar Script Ingesta
        run: ./venv/Scripts/python.exe src/edu_pad/main_ingesta.py


  auto_commit:
    name: Auto Commit
    runs-on: windows-latest
    needs: run_script
    permissions:
      contents: write
    steps:
      - name: Paso 9 - Guardar el commit con el ultimo cambio
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Actividad 2"
          commit_user_name: "DanyC2003"
          commit_user_email: "danielacoronado0109@gmail.com"
          commit_author: "Daniela Coronado <daniela.coronado@est.iudigital.edu.co> Y Camilo Olea <camilo.olea@est.iudigital.edu.co>"